variables:
  DOCKER_HOST: tcp://docker:2375

stages:
  - test


test:
  stage: test
  image: cypress/base:18.12.1
  before_script:
    - npm install
    - export DISPLAY=:99
    - Xvfb :99 -screen 0 1024x768x16 &

  script:
    - $(npm bin)/cypress run
  artifacts:
    paths:
      - cypress/videos/
      - cypress/screenshots/  
